# https://www.home-assistant.io/integrations/http/
#ip_ban_enabled: true
login_attempts_threshold: 5
server_port: 29000
use_x_forwarded_for: true
trusted_proxies:
  - 172.16.10.0/24
cors_allowed_origins:
  - https://objects.githubusercontent.com
  - https://github.com
  - https://google.com
  - https://www.home-assistant.io
#ssl_certificate: /letsencrypt/live/landshut.ddns.net/fullchain.pem
#ssl_key: /letsencrypt/live/landshut.ddns.net/privkey.pem
